# Generated by Django 3.0.7 on 2020-12-29 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_logic', '0003_auto_20201229_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='admin',
        ),
    ]
