# Generated by Django 3.0.7 on 2021-01-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_logic', '0005_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='assassinated',
            field=models.BooleanField(default=False),
        ),
    ]
