# Generated by Django 3.0.7 on 2021-02-10 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_logic', '0007_auto_20210210_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_logic.Game'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='round',
            name='assassinated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_logic.Player'),
        ),
        migrations.AlterField(
            model_name='round',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_logic.Game'),
        ),
        migrations.AlterField(
            model_name='roundpairing',
            name='assassin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_logic.Player'),
        ),
        migrations.AlterField(
            model_name='roundpairing',
            name='round_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_logic.Round'),
        ),
        migrations.AlterField(
            model_name='roundpairing',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='game_logic.Player'),
        ),
    ]
