# Generated by Django 3.0.5 on 2020-06-14 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personalinfo',
            table=None,
        ),
    ]
