# Generated by Django 3.0.5 on 2020-10-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20200616_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=models.CharField(max_length=300),
        ),
    ]
